### ISSUE TITLE
doesn't accept values on command line

### ISSUE THREAD

**Issue by gregzuro** [Urban4M/go-flagged#1]
Perhaps I am missing something, but this doesn't actually recognize values supplied on the command line as usage suggests.

```
$ cd go/src/github.com/Urban4M/go-flagged/ex/
$ go build
$ ./ex -a.float=23.53
...
2015/05/28 21:37:12 {aString: aBool:false aFloat:0 ints:{anInt:0 anInt64:0 anUint:0 anUint64:0} values:{aString:default string aBool:true aFloat:123.456 ints:{anInt:-1 anInt64:-2 anUint:1 anUint64:2}} envs:{aString:default string aBool:true aFloat:123.456 ints:{anInt:-1 anInt64:-2 anUint:1 anUint64:2}} named:{aString:default string aBool:true aFloat:123.456 ints:{anInt:-1 anInt64:-2 anUint:1 anUint64:2}}}
...
Usage of ./ex:
  -a.bool=false: A Bool.
  -a.float=0: A Float.
  -a.string="": A String.
...
```

**Comment by rnix** [comment]
You're not missing something. It appears i've broken something before pushing to github. I have a working build locally which i'll push later this morning after i identify the exact problem.

**Comment by rnix** [comment]
Sorry about that. On the plus-side, the library was working fine. It just required that flag.Parse() be called to perform the actual parsing of the options.

**Comment by gregzuro** [comment]
Thanks!  Much better, now. :)
